=== Milly/runtray-ps/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/Milly/runtray-ps/v1.1.0/schemas/config.schema.json",
  "title": "RunTray Configuration",
  "type": "object",
  "required": [
    "executable"
  ],
  "properties": {
    "name": {
      "title": "Program Name",
      "description": "Used for the shortcut filename and the program title.",
      "type": "string",
      "minLength": 1,
      "maxLength": 127,
      "examples": ["ping-local"],
      "pattern": "^[^<>:\"/\\\\|?*]*$"
    },
    "description": {
      "title": "Service Description",
      "description": "Written in the description field of the shortcut.",
      "type": "string",
      "default": "",
      "examples": ["Pinging localhost continuously."]
    },
    "executable": {
      "title": "Executable Path",
      "type": "string",
      "minLength": 1,
      "examples": ["%WinDir%\\System32\\ping.exe"],
      "pattern": "^([a-zA-Z]+:)?[^<>:\"/|?*]*$"
    },
    "arguments": {
      "title": "Executable Arguments",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": [],
      "examples": [["-t", "127.0.0.1"]]
    },
    "workingdirectory": {
      "title": "Working Directory",
      "type": "string",
      "minLength": 1,
      "default": ".",
      "examples": ["%USERPROFILE%"]
    },
    "shutdownwait": {
      "title": "Wait time in milliseconds after sending Ctrl-C",
      "type": "integer",
      "minimum": 10,
      "default": 2000
    }
  }
}

=== Milly/runtray-ps/tests/fixtures/config/sleep5.json
{
    "$schema": "https://raw.githubusercontent.com/Milly/runtray-ps/v1.1.0/schemas/config.schema.json",
    "name": "sleep5",
    "description": "sleep 5 seconds",
    "executable": "powershell.exe",
    "arguments": [
        "-NoProfile",
        "-ExecutionPolicy", "RemoteSigned",
        "-Command", "&{for($i=5;0 -lt $i;--$i){echo $i;sleep 1}echo 'done'}"
    ]
}

=== Milly/runtray-ps/examples/ping-local.json
{
    "$schema": "https://raw.githubusercontent.com/Milly/runtray-ps/v1.1.0/schema.json",
    "name": "ping-local",
    "description": "Pinging localhost continuously.",
    "executable": "%WinDir%\\System32\\ping.exe",
    "arguments": ["-t", "127.0.0.1"],
    "workingdirectory": "%USERPROFILE%",
    "shutdownwait": 2000
}
